echo "[INFO] Calculating witness..."

# Define file/directory paths
WASM_FILE="build/ProveCommitmentWithSignature_js/ProveCommitmentWithSignature.wasm" # Check this path reflects your circom output structure
INPUT_JSON="build/input.json"
WITNESS_FILE="build/witness.wtns"
WITNESS_GEN_SCRIPT="build/ProveCommitmentWithSignature_js/generate_witness.js" # JS helper for WASM witness calculation

# Ensure required input files exist
if [ ! -f "$WASM_FILE" ]; then echo "[ERROR] WASM file not found: $WASM_FILE"; exit 1; fi
if [ ! -f "$INPUT_JSON" ]; then echo "[ERROR] Input JSON not found: $INPUT_JSON"; exit 1; fi
if [ ! -f "$WITNESS_GEN_SCRIPT" ]; then echo "[ERROR] Witness generation script not found: $WITNESS_GEN_SCRIPT"; exit 1; fi

# Calculate the witness using the JS helper generated by circom
node $WITNESS_GEN_SCRIPT \
     $WASM_FILE \
     $INPUT_JSON \
     $WITNESS_FILE

# Verify witness file creation
if [ ! -f "$WITNESS_FILE" ]; then
    echo "[ERROR] Failed to generate witness file: $WITNESS_FILE. Check output above."
    exit 1
fi
echo "[SUCCESS] Witness generated: $WITNESS_FILE"